### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by jeremejevs** [ClydeDroid/rofi-bluetooth#1]
Thanks for making this!

I went ahead and [published rofi-bluetooth on AUR](https://aur.archlinux.org/packages/rofi-bluetooth-git/). Patched `rofi_command` to make it respect user rofi settings. Happy to hand over the package!

**Comment by ClydeDroid** [comment]
Oh excellent! I meant to do this but never got around to it. I haven't managed a package on AUR before but I wouldn't mind taking it over to get some practice! My username on AUR is clydedroid.
I'll update the README to link to it too. Thanks so much!

**Comment by jeremejevs** [comment]
Done! :wink: Looks like "handing over" isn't a thing on AUR, so added you as a co-maintainer instead.

**Comment by alecmev** [comment]
Hi! Just in case, it isn't necessary to [bump](https://aur.archlinux.org/cgit/aur.git/commit/?h=rofi-bluetooth-git&id=b93a0c92707bfa86daca2fe10a9391f1d9508fc2) `-git` packages :wink: Most AUR helpers, e.g. `paru` or `yay`, check for new commits and rebuild the package if they find any.

**Comment by ClydeDroid** [comment]
Aha... good to know! Less work for me then :smile:
