### ISSUE TITLE
Polybar module toggles continuously when one bluetooth device is connected

### ISSUE THREAD

**Issue by Samaruq** [ClydeDroid/rofi-bluetooth#10]
For some reason the polybar module using `rofi-bluetooth --status`, disappears and reappears periodically with the time interval set in the polybar module when one device is connected. However, when two devices are connected, it does not toggle.

Some context:
```console
$ polybar --version
polybar 3.5.4
```

Polybar module config:
```
[module/bluetooth]
type = custom/script
exec = rofi-bluetooth --status
interval = 1
click-left = rofi-bluetooth &
format-background = ${color.mb}
format-padding = ${layout.module-padding}
```

Rofi-bluetooth version:
```console
$ yay -Q rofi-bluetooth-git
rofi-bluetooth-git r18.3b85658-3
```

While I don't know  exactly what caused this behaviour, I was able to fix it by adding
```bash
        printf "\n"
```
at [this line](https://github.com/ClydeDroid/rofi-bluetooth/blob/master/rofi-bluetooth#L204).

So I assume when one device was connected, the buffer did not flush properly half of the time.

P.S. this behaviour started after updating this morning.

**Comment by ClydeDroid** [comment]
Weird... I'm not able to reproduce this on my end, but adding that line doesn't seem to break anything, so I'll go ahead and open a PR with it!
