### ISSUE TITLE
Menu exits after each state-change

### ISSUE THREAD

**Issue by srinskit** [ClydeDroid/rofi-bluetooth#3]
Currently turning bluetooth on and connecting to a device looks like this
1. Open rofi bluetooth
1. Power > on
1. Menu closes; Open rofi bluetooth again
1. Device > Connected > yes
1. Menu closes

The menu closes after each state-change. Is this because it takes time to perform the state-change and reflecting it live isn't feasible? It would be much more convenient if it returned to the main rofi-bluetooth menu.

**Comment by ClydeDroid** [comment]
Yeah, it takes a little bit of time to reflect the state changes, but I could probably rework it a little to bring the menu back up, and then just add an exit option to the bottom. That would definitely be more convenient!
I'll see if I can get some time to work on it this weekend!

**Comment by ClydeDroid** [comment]
Should be working now, give it a shot and let me know what you think!

**Comment by srinskit** [comment]
Neat! Works great for me! 

Does the menu have to exit and reappear while the state changes? Can it not stay on the menu and indicate progress with "Connecting" or "Turning on/off"? Does sound like a lot of rework.
